language: node_js
node_js:
- 6.1
addons:
  sauce_connect: true
env:
  matrix:
    secure: LMf5CbdwYDoy+xaWVr3Ixa0xfeE9XSUTWVfF5aNJSnMk8sWE03+kBqC0u6gA9FXr8zVMEgf9gjycHJEphxrbLGN+L9KydK3qwIdMiakUIKaGAEPbPLnJhFl74Kk9nx5BRD4fpOoNlYD2F4kJk93/KgL4x6GxGxOpUjwaGtIW7lEGQF88dJXR1bKdZzKjKjGK5w0QWXl4VQ5zyx/QJ4qBrSGhdiHtjaxh/QXDLYsAcWfJQh3KPYauLhFm4x/bPX7m42OcWR51wwnS3PKQooSXxftOKxKIVXyS24mgKovPbq/PGCp7UVOFrfGoCtgqcEg6eW3l2Sa+XNZQXHYcbUn/ZBNgkGzzugFDO3JigbrRP2dXy7psUFHPvFcSlIgvPNqeZg7QhGWA2106ng0mfvBWdbGcj8UM1+gS5prQg2+VD3pC7+30d7N/y0WZFM0qQ4e/9Wj61SaBo62hYpxaqkFpKdx+F2hC6U2j4orXGTp6AVobcLqPrxPhy+FqUQETnT7x/8oJP433cQsDu3TiDhuFKo6ebVzMVTIZWl8FJ4JIJ1a288Sj6A5ZliosRS1/Z+xXZ9wRR+IEm/Uamcg896F1ee+NEZc7IBeD+FlJ7jFAmv8dj7/zd8g9spl/F6aiR0BCzQd6hEgq5JHmtfsiaIwD0KDP7ugiucgxLMFd5SdNyjg=
