language: node_js
node_js:
- 6.1
addons:
  sauce_connect: true
env:
  matrix:
    secure: SqiIvtse8kS6OW3Ahwtsz5oac2BlZEYJ8Yk7ZaqviOca8CyfrWec4ylQovhY9QhQuwwssGKPNkq6StTlFLt0aEWj8aLxPr55wa0uRVXOE4Of2B1GFkQHkLaU4IPw9DCeuSbZ9mV/CuakD75PP3rONcy82em0eUEcxZNjJuFQfT6sS4KEMYvx/YI/R3YjgSOTzMAR6kp752grxQcH1UZHvnTHqcFVjHD69bErxUqainfVfpQ3WDy/zdu8ua8xerLvTuLZW8bdLN/v9bMwRTMcYKPhtijCC21ut7ycRbKrdRIVU2IcHw3pY4iwUZOSeHpNj/x8O+WGOZJNzOyx5SW4G+QdNsahxHaO4kjbSiQSCFEysL3pOK6WmIbINM+LNvl3QgZe3WSAHN028FDZpCtUgYPrgxomm/FEYuzSBIY8+EleMlIXluS99ndj1GD9Wdw1Iu8cYkMs9kqBIQKnIdHK8vKCOeFho1sEfSV+8o44POLSaGfqhIqOx5ujBFaqFY9GWChb/m2EAbtnqYt6SnzVxQZhoiBt6dFRuEke3scu4RRw4i6hAC7vEFACicrSd/ok7ttiIlU1nhj5NfOVfgsTpVAoXyTOad7xn2oDYMRwvvzrQcYxE+vOACxatCKbTejS6eOwa1LWlFJRp2sY/NHReuNzR2I+4zABcTq6f1znMII=
